# on 1994/12/06 18:02:02, coelho did: ...
git-svn-id: http://svn.cri.ensmp.fr/svn/nlpmake@31 0884f79e-42f2-0310-bc61-a3b21e0d3bdb

diff --git a/makes/pips-makemake b/makes/pips-makemake
--- a/makes/pips-makemake
+++ b/makes/pips-makemake
@@ -1,7 +1,7 @@
 #! /bin/sh
 #! /bin/sh -vx
 #
-# $RCSfile: pips-makemake,v $ ($Date: 1994/12/06 16:32:07 $) version $Revision$, got on %D%, %T%
+# $RCSfile: pips-makemake,v $ ($Date: 1994/12/06 18:02:02 $) version $Revision$, got on %D%, %T%
 # %A%
 
 # Automatic generation of Makefile for the PIPS project
@@ -352,7 +352,7 @@ else
 CFILES=		$(TARGET_CFILES)
 OBJECTS=	$(TARGET_OBJECTS)
 INCLUDES=	$(TARGET_HEADERS)
-SOURCES= 	$(MAKEFILE) $(CONFIG_FILE) $(INCLUDES) $(CFILES)
+SOURCES= 	$(CONFIG_FILE) $(INCLUDES) $(CFILES)
 #
 TARGETDIR=	$(BINSRCDIR)/$(TARGET)
 #
@@ -368,14 +368,20 @@ $(BIN_TARGET): $(OBJECTS) $(INC_TARGET)
 	$(LINK) $(BIN_TARGET) $(OBJECTS) $(TARGET_LIBS)
 
 install: $(INC_TARGET) $(BIN_TARGET)
-	@test \`echo *.a | wc -w\` -gt 0 && \\
+	@touch _tmp_hack.a
+	@test \`echo *.a | wc -w\` -eq 1 || \\
 	{ \\
-	  echo "install failed: additional local libraries prevent it" >&2;\\
+	  echo "install failed: local libraries prevent it" >&2;\\
+	  $(RM) _tmp_hack.a ; \\
 	  exit 1;\\
 	}
+	@$(RM) _tmp_hack.a
 	[ -d $(TARGETDIR) ] || { mkdir $(TARGETDIR) $(TARGETDIR)/SCCS ; }
 	-cd $(TARGETDIR) ; \\
-	find . -name SCCS -exec echo sh -c \" cd \`dirname '{}' \` \; sccs edit SCCS \" \; | sh; ls -lagR
+	for s in \`find . -name SCCS -print \` ; \\
+	do \\
+	  (echo \$\$s ; cd \`dirname \$\$s\` ; sccs edit SCCS ;); \\
+	done
 	-$(RM) $(TARGETDIR)/*
 	cp -r $(SOURCES) $(TARGETDIR)
 	echo ""; echo; \\
@@ -384,20 +390,10 @@ install: $(INC_TARGET) $(BIN_TARGET)
 	cd $(TARGETDIR) ; \\
 	for m in \`find $(SOURCES) -type f -print\` ;\\
 	do \\
-	  cd \$\$PWD/\`dirname \$\$m\` ; \\
+	  ( cd \$\$PWD/\`dirname \$\$m\` ; \\
 	  module=\`basename \$\$m\` ; \\
-	  if ! sccs prs \$\$module > /dev/null 2>&1 ;\\
+	  if sccs prs \$\$module > /dev/null 2>&1 ;\\
 	  then \\
-	    echo sccs create \$\$module;  \\
-	    sccs create \$\$module;  \\
-	    if cmp -s ,\$\$module \$\$module ; \\
-	    then \\
-	      rm ,\$\$module ; \\
-	    else \\
-	      echo sccs failed with \$\$module ; \\
-	      exit 1; \\
-	    fi ; \\
-	  else \\
 	    echo sccs delget -y\"\$\$comments\" \$\$module; \\
 	    sccs delget -y"\$\$comments" \$\$module || \\
 	    { \\
@@ -410,7 +406,17 @@ install: $(INC_TARGET) $(BIN_TARGET)
 	        exit 1; \\
 	      fi ; \\
 	    } \\
-	  fi ;\\
+	  else \\
+	    echo sccs create \$\$module;  \\
+	    sccs create \$\$module;  \\
+	    if cmp -s ,\$\$module \$\$module ; \\
+	    then \\
+	      rm ,\$\$module ; \\
+	    else \\
+	      echo sccs failed with \$\$module ; \\
+	      exit 1; \\
+	    fi ; \\
+	  fi ; ) ;\\
 	done ; \\
 	for module in \`sccs tell\` ; \\
 	do \\
