# on 1994/11/21 16:36:02, coelho did: make depend added to the installation
git-svn-id: http://svn.cri.ensmp.fr/svn/pips/trunk@695 32a0c1e6-9308-0410-80dd-f9d2257a62c7

diff --git a/src/Scripts/dev/pips-makemake b/src/Scripts/dev/pips-makemake
--- a/src/Scripts/dev/pips-makemake
+++ b/src/Scripts/dev/pips-makemake
@@ -1,7 +1,7 @@
 #! /bin/sh
 #! /bin/sh -vx
 #
-# $RCSfile: pips-makemake,v $ ($Date: 1994/08/28 22:14:22 $) version $Revision$, got on %D%, %T%
+# $RCSfile: pips-makemake,v $ ($Date: 1994/11/21 16:36:02 $) version $Revision$, got on %D%, %T%
 # %A%
 
 # Automatic generation of Makefile for the PIPS project
@@ -109,6 +109,9 @@
 #	Bon, le rajout d'un find dans le do a amélioré les choses.
 #	RK 17/06/1994.
 # - cproto used without the .i intermediate generation, FC 28/08/94
+# - Makefile is not considered as a source anymore, FC
+# - the installation takes care of files that are removed from the SOURCES, FC
+#
 # wish:
 #
 
@@ -229,7 +232,7 @@ cat >> $MAKEFILE <<%
 CFILES=		$(MAIN).c $(LIB_CFILES)
 OBJECTS=	$(MAIN).o $(LIB_OBJECTS)
 INCLUDES=	$(LIB_HEADERS)
-SOURCES= 	$(MAKEFILE) $(CONFIG_FILE) $(INCLUDES) $(CFILES)
+SOURCES= 	$(CONFIG_FILE) $(INCLUDES) $(CFILES)
 #
 TARGETDIR=	$(LIBSRCDIR)/$(TARGET)
 #
@@ -272,42 +275,55 @@ $(BIN_TARGET): $(LIB_TARGET) $(MAIN).o
 	@echo 
 
 install: $(INC_TARGET) $(LIB_TARGET)
-	@if test \`ls *.a | wc -w\` -gt 1 ; then echo install failed: additional local libraries prevent it >&2; exit 1; fi
-	if [ ! -d $(TARGETDIR) ] ; \\
-	then mkdir $(TARGETDIR) ; \\
+	@if test \`ls *.a | wc -w\` -gt 1 ; \\
+	then \\
+	  echo "install failed: additional local libraries prevent it" >&2;\\
+	  exit 1;\\
 	fi
+	[ -d $(TARGETDIR) ] || { mkdir $(TARGETDIR) $(TARGETDIR)/SCCS ; }
 	-cd $(TARGETDIR) ; sccs edit SCCS
-	-$(RM) $(TARGETDIR)/* pips
+	-$(RM) $(TARGETDIR)/*
 	cp $(SOURCES) $(TARGETDIR)
 	echo ""; echo; \\
 	echo -n "Description of changes: " ; \\
-	read comments ;\\
+	read comments ;
 	cd $(TARGETDIR) ; \\
 	for module in $(SOURCES) ;\\
 	do \\
-		if [ ! -f SCCS/s.\$\$module ] ;\\
-		then \\
-			echo sccs create \$\$module;  \\
-			sccs create \$\$module;  \\
-			if cmp -s ,\$\$module \$\$module ; \\
-			then echo sccs properly initialized for \$\$module ; \\
-				rm ,\$\$module ; \\
-			else echo sccs failed with \$\$module ; \\
-				exit 1; \\
-			fi ; \\
-		else \\
-			echo sccs -y\"\$\$comments\" delget \$\$module; \\
-			if sccs delget -y"\$\$comments" \$\$module; \\
-			then echo sccs delget succeeded; \\
-			else status=\$\$? ; \\
-				if [ \$\$status -eq 255 ] ; \\
-					then echo sccs delget return code \$\$status ; \\
-					else echo sccs delget unusual return code \$\$status ; \\
-						exit 1; \\
-				fi ; \\
-			fi ; \\
-		fi ;\\
-	done
+	  if [ ! -f SCCS/s.\$\$module ] ;\\
+	  then \\
+	    echo sccs create \$\$module;  \\
+	    sccs create \$\$module;  \\
+	    if cmp -s ,\$\$module \$\$module ; \\
+	    then \\
+	      rm ,\$\$module ; \\
+	    else \\
+	      echo sccs failed with \$\$module ; \\
+	      exit 1; \\
+	    fi ; \\
+	  else \\
+	    echo sccs delget -y\"\$\$comments\" \$\$module; \\
+	    sccs delget -y"\$\$comments" \$\$module || \\
+	    { \\
+	      status=\$\$? ; \\
+	      if [ \$\$status -eq 255 ] ; \\
+	      then \\
+	        echo sccs delget return code \$\$status ; \\
+	      else \\
+	        echo sccs delget unusual return code \$\$status ; \\
+	        exit 1; \\
+	      fi ; \\
+	    } \\
+	  fi ;\\
+	done ; \\
+	for module in \`sccs tell\` ; \\
+	do \\
+	  echo "no more \$\$module file" ; \\
+	  sccs unedit \$\$module ; \\
+	  $(RM) \$\$module ; \\
+	done ;
+	cp $(MAKEFILE) $(TARGETDIR)/Makefile
+	$(MAKE) -C $(TARGETDIR) depend
 	$(MAKE) quick-install
 
 quick-install:
@@ -320,8 +336,8 @@ $(LIBDIR)/$(LIB_TARGET): $(LIB_TARGET)
 	ranlib $(LIBDIR)/$(LIB_TARGET)
 
 clean:
-	-$(RM) TAGS $(OBJECTS) $(INC_TARGET) $(LIB_TARGET) $(BIN_TARGET) $(DERIVED_HEADERS) *.~[0-9]~\\
-		$(LIB_IFILES)
+	-$(RM) TAGS $(OBJECTS) $(INC_TARGET) $(LIB_TARGET) \\
+		 $(BIN_TARGET) $(DERIVED_HEADERS) *.~[0-9]~ $(LIB_IFILES)
 
 INC_CFILES = $(LIB_CFILES)
 
@@ -351,42 +367,55 @@ $(BIN_TARGET): $(OBJECTS) $(INC_TARGET)
 	$(LINK) $(BIN_TARGET) $(OBJECTS) $(TARGET_LIBS)
 
 install: $(INC_TARGET) $(BIN_TARGET)
-	@if test \`ls *.a | wc -w\` -gt 1 ; then echo install failed: additional local libraries prevent it >&2; exit 1; fi
-	if [ ! -d $(TARGETDIR) ] ; \\
-	then mkdir $(TARGETDIR) ; \\
+	@if test \`ls *.a | wc -w\` -gt 1 ; \\
+	then \\
+	  echo "install failed: additional local libraries prevent it" >&2;\\
+	  exit 1;\\
 	fi
+	[ -d $(TARGETDIR) ] || { mkdir $(TARGETDIR) $(TARGETDIR)/SCCS ; }
 	-cd $(TARGETDIR) ; sccs edit SCCS
 	-$(RM) $(TARGETDIR)/*
-	cp -r $(SOURCES) $(TARGETDIR)
+	cp $(SOURCES) $(TARGETDIR)
 	echo ""; echo; \\
 	echo -n "Description of changes: " ; \\
 	read comments ;\\
 	cd $(TARGETDIR) ; \\
 	for module in `find $(SOURCES) -print` ;\\
 	do \\
-		if [ ! -f SCCS/s.\$\$module ] ;\\
-		then \\
-			echo sccs create \$\$module;  \\
-			sccs create \$\$module;  \\
-			if cmp -s ,\$\$module \$\$module ; \\
-			then echo sccs properly initialized for \$\$module ; \\
-				rm ,\$\$module ; \\
-			else echo sccs failed with \$\$mocule ; \\
-				exit 1; \\
-			fi ; \\
-		else \\
-			echo sccs -y\"\$\$comments\" delget \$\$module; \\
-			if sccs delget -y"\$\$comments" \$\$module; \\
-			then echo sccs delget succeeded; \\
-			else status=\$\$? ; \\
-				if [ \$\$status -eq 255 ] ; \\
-					then echo sccs delget return code \$\$status ; \\
-					else echo sccs delget unusual return code \$\$status ; \\
-						exit 1; \\
-				fi ; \\
-			fi ; \\
-		fi ;\\
+	  if [ ! -f SCCS/s.\$\$module ] ;\\
+	  then \\
+	    echo sccs create \$\$module;  \\
+	    sccs create \$\$module;  \\
+	    if cmp -s ,\$\$module \$\$module ; \\
+	    then \\
+	      rm ,\$\$module ; \\
+	    else \\
+	      echo sccs failed with \$\$module ; \\
+	      exit 1; \\
+	    fi ; \\
+	  else \\
+	    echo sccs delget -y\"\$\$comments\" \$\$module; \\
+	    sccs delget -y"\$\$comments" \$\$module || \\
+	    { \\
+	      status=\$\$? ; \\
+	      if [ \$\$status -eq 255 ] ; \\
+	      then \\
+	        echo sccs delget return code \$\$status ; \\
+	      else \\
+	        echo sccs delget unusual return code \$\$status ; \\
+	        exit 1; \\
+	      fi ; \\
+	    } \\
+	  fi ;\\
+	done ; \\
+	for module in \`sccs tell\` ; \\
+	do \\
+	  echo "no more \$\$module file" ; \\
+	  sccs unedit \$\$module ; \\
+	  $(RM) \$\$module ; \\
 	done
+	cp $(MAKEFILE) $(TARGETDIR)/Makefile
+	$(MAKE) -C $(TARGETDIR) depend
 	$(MAKE) quick-install
 
 quick-install: $(BINDIR)
@@ -394,7 +423,8 @@ quick-install: $(BINDIR)
 	cp $(BIN_TARGET) $(BINDIR)
 
 clean:
-	-$(RM) TAGS $(OBJECTS) $(BIN_TARGET) $(INC_TARGET) $(DERIVED_HEADERS) *.~[0-9]~
+	-$(RM) TAGS $(OBJECTS) $(BIN_TARGET) \\
+		$(INC_TARGET) $(DERIVED_HEADERS) *.~[0-9]~
 
 INC_CFILES = $(TARGET_CFILES)
 
