# on 1995/08/07 11:11:24, coelho did: *** empty log message ***
git-svn-id: http://svn.cri.ensmp.fr/svn/pips/trunk@1528 32a0c1e6-9308-0410-80dd-f9d2257a62c7

diff --git a/src/Scripts/dev/pips-makemake b/src/Scripts/dev/pips-makemake
--- a/src/Scripts/dev/pips-makemake
+++ b/src/Scripts/dev/pips-makemake
@@ -1,7 +1,7 @@
 #! /bin/sh
 #! /bin/sh -vx
 #
-# $RCSfile: pips-makemake,v $ ($Date: 1995/08/04 16:58:25 $, )
+# $RCSfile: pips-makemake,v $ ($Date: 1995/08/07 11:11:24 $, )
 # version $Revision$
 #
 # Automatic generation of Makefile for the PIPS project
@@ -19,14 +19,9 @@ help()
 	$USAGE
 	version $Revision$
 	builds a makefile from a config.makefile for pips
-	  -l: libraries
-	  -p: passes
-	  -s: scripts
-	  -r: runtime
-	  -D: for development directories
-	  -P: for production directories
-	  -c: for the current directory
-	  -a: for all directories if a given type
+	  -l|p|s|r: libraries|passes|scripts|runtime
+	  -D|P: for Development|Production directories
+	  -c|a: for the current|all directory(ies)
 	  -h: this help
 	END_OF_HELP
 }
@@ -67,16 +62,41 @@ shift `expr $OPTIND - 1`
 [ $# -eq 0 ] || usage 3 "$# remaining parameters"
 [ "${DIRTYPE}" ] || usage 4 "must specify -l|p|s|r"
 
-# delayed to ensure that DIRSIDE and DIRTYPE are available
+# delayed to ensure that DIRTYPE is available
 
 [ "$ALL" ] && DIRS=${DIRSIDE}/${DIRTYPE}/*
+
+# directories for quick-install:
+#
+# install_file_dir for usual files
+# install_lib_dir for library files
+# install_exe_dir for executable files
+
+install_file_dir=$INCLUDEDIR
+install_lib_dir=$LIBDIR
+install_exe_dir=$BINDIR
+
+case $DIRTYPE in
+  Lib) : ;;
+  Passes) : ;;
+  Scripts) install_file_dir=$UTILDIR ;
+           install_lib_dir=$UTILDIR ;
+           install_exe_dir=$UTILDIR ;;
+  Runtime) install_file_dir=$EXTEDIR ;
+           install_exe_dir=$EXTEDIR ;
+           install_lib_dir=$EXTEDIR ;;
+  *) usage 5 "unexpected directory type $DIRTYPE"
+esac
+
+current_directory=`pwd`
 
 ### main loop
 for dir in $DIRS
 do
-  ( cd $dir
+  cd $current_directory
+  cd $dir
   
-  [ -f $CONFIG_FILE ] || usage 5 "no $CONFIG_FILE in $dir" ;
+  [ -f $CONFIG_FILE ] || usage 6 "no $CONFIG_FILE in $dir" ;
 
   # needed because of f.. - in directory names...
   dir_real_name=`basename \`pwd\``
@@ -120,6 +140,12 @@ do
 #
 TARGET=		$dir_real_name
 TARGETDIR=	$(SRCDIR)/$DIRTYPE/$(TARGET)
+#
+# installation directories for quick-install
+#
+INSTALL_FILE_DIR= ${install_file_dir}
+INSTALL_LIB_DIR=  ${install_lib_dir}
+INSTALL_EXE_DIR=  ${install_exe_dir}
 # (obsolete?)
 MAIN=		main
 #
@@ -146,6 +172,11 @@ MAKEFILE=	$MAKEFILE
 # to override sun's default rule
 .SCCS_GET:
 
+check_os:
+	@if test -n "$(PIPS_CHECK_OS)"; \\
+	then echo "Cannot run make under this OS release"; \\
+	     echo "$(PIPS_CHECK_OS)"; exit 1; \\
+	fi
 #
 # begin of $CONFIG_FILE inclusion
 #
@@ -173,18 +204,22 @@ BIN_TARGET=	$(TARGET)
 INC_TARGET=	$(TARGET).h
 #
 
-.INIT: $MAKEFILE 
-	@if test -n "$(PIPS_CHECK_OS)"; \\
-	then echo "Cannot run make under this OS release"; \\
-	     echo "$(PIPS_CHECK_OS)"; exit 1; \\
-	fi
+.INIT: $MAKEFILE check_os
+
+$(LIB_TARGET): $(LIB_OBJECTS) $(TARGET_OBJECTS)
+	$(RM) $(LIB_TARGET)
+	$(ARCHIVE) $(LIB_TARGET) \\
+		\`lorder $(LIB_OBJECTS) $(TARGET_OBJECTS)| tsort\`
+	ranlib $(LIB_TARGET)
 
 %
 
 [ $DIRTYPE = 'Scripts' ] && cat >> $MAKEFILE <<%
 
 SOURCES=	$(SCRIPTS) $(FILES) $(SFILES) $(CONFIG_FILE)
-RUNS=		$(SCRIPTS) $(FILES) $(RFILES)
+RUNS=		$(SCRIPTS) $(RFILES)
+
+all: .runable
 
 .runable: $(SCRIPTS)
 	-[ "$(SCRIPTS)" ] && chmod a+x $(SCRIPTS)
@@ -194,8 +229,10 @@ check_install:
 	@echo ok
 
 .quick-install: .runable $(RFILES)
-	( cd $(UTILDIR) ; $(RM) $(RUNS) )
-	cp $(RUNS) $(UTILDIR)
+	( cd $(INSTALL_EXE_DIR) ; $(RM) $(RUNS) )
+	cp $(RUNS) $(INSTALL_EXE_DIR)
+	( cd (INSTALL_FILE_DIR) ; $(RM) $(FILES) )
+	cp $(FILES) $(INSTALL_FILE_DIR)
 	touch .quick-install
 
 .INIT: $(MAKEFILE)
@@ -213,31 +250,15 @@ SOURCES= 	$(CONFIG_FILE) $(INCLUDES) $(CFILES)
 #
 all: $(LIB_TARGET)
 
-test: all $(DEVEDIR)/Passes/pips/pips.o
-	$(LINK) pips $(DEVEDIR)/Passes/pips/pips.o $(PIPS_LIBS)
+test: all 
+	$(LINK) pips -lpips $(PIPS_LIBS)
 	@echo 
 
 WPIPS_DEVEDIR=$(DEVEDIR)/Passes/wpips
-# Extrait ici le noms des .o et des bibliothèques necessaires à wpips. 
-# C'est très crado :-) ! RK.
-# Probablement que ce serait mieux de faire un make -n dans wpips pour
-# avoir l'instruction exacate à utiliser...
-wtest: all $(WPIPS_DEVEDIR)/wpips.o
-	$(LINK) wpips -L$(WPIPS_DEVEDIR) -L$(OPENWINHOME)/lib \\
-	\`perl -ne 'chop; if (\$\$trouve != 1) \\
-		{ /TARGET_OBJECTS/ && do {\$\$trouve = 1; print;}} \\
-		else { s/\x5c// && print || print && exit(0);};' \\
-		$(WPIPS_DEVEDIR)/config.makefile \\
-	| perl -ne 's/.*=//; s/[\\t\\r\\n \x5c]+/ /g; \\
-		s,([^ ]+),$(WPIPS_DEVEDIR)/\$\$1,g; print' \` \\
-	\`grep '^TARGET_LIB' $(WPIPS_DEVEDIR)/config.makefile \\
-		| sed -e 's/.*=/echo /' -e 's/[()]//g' | sh \`
-	@echo 
 
-$(LIB_TARGET): $(LIB_OBJECTS)
-	$(RM) $(LIB_TARGET)
-	$(ARCHIVE) $(LIB_TARGET) \`lorder $(LIB_OBJECTS) | tsort\`
-	ranlib $(LIB_TARGET)
+wtest: all 
+	$(LINK) wpips -L$(OPENWINHOME)/lib -lwpips $(PIPS_LIBS)
+	@echo 
 
 $(BIN_TARGET): $(LIB_TARGET) $(MAIN).o
 	$(LINK) $(TARGET) $(MAIN).o $(LIB_TARGET) $(PIPS_LIBS)
@@ -256,8 +277,8 @@ check_install:
 # header installed only if different.
 # should avoid some recompilations if headers are not touched.
 .quick-install: $(INC_TARGET) $(LIB_TARGET)
-	@pips_install_file $(INC_TARGET) $(INCLUDEDIR)/$(INC_TARGET)
-	@pips_install_file $(LIB_TARGET) $(LIBDIR)/$(LIB_TARGET) 
+	@pips_install_file $(INC_TARGET) $(INSTALL_FILE_DIR)/$(INC_TARGET)
+	@pips_install_file $(LIB_TARGET) $(INSTALL_LIB_DIR)/$(LIB_TARGET) 
 	ranlib $(LIBDIR)/$(LIB_TARGET)
 	touch .quick-install
 
@@ -284,10 +305,10 @@ TARGETDIR=	$(BINSRCDIR)/$(TARGET)
 #
 TARGET_IFILES=	$(TARGET_CFILES:.c=.i)
 #
-INSTALL_TARGETS=	$(INC_TARGET) $(BIN_TARGET)
+INSTALL_TARGETS=	$(INC_TARGET) $(BIN_TARGET) $(LIB_TARGET)
 
-$(BIN_TARGET): $(OBJECTS) $(INC_TARGET)
-	$(LINK) $(BIN_TARGET) $(OBJECTS) $(TARGET_LIBS)
+$(BIN_TARGET): $(INC_TARGET) $(LIB_TARGET)
+	$(LINK) $(BIN_TARGET) $(LIB_TARGET) $(TARGET_LIBS)
 
 check_install:
 	@touch _tmp_hack.a
@@ -300,12 +321,14 @@ check_install:
 	@$(RM) _tmp_hack.a
 
 .quick-install: $(INSTALL_TARGETS) $(BINDIR)
-	@pips_install_file $(INC_TARGET) $(INCLUDEDIR)/$(INC_TARGET)
-	@pips_install_file $(BIN_TARGET) $(BINDIR)/$(BIN_TARGET)
+	@pips_install_file $(INC_TARGET) $(INSTALL_FILE_DIR)/$(INC_TARGET)
+	@pips_install_file $(LIB_TARGET) $(INSTALL_LIB_DIR)/$(LIB_TARGET)
+	ranlib $(INSTALL_LIB_DIR)/$(LIB_TARGET)
+	@pips_install_file $(BIN_TARGET) $(INSTALL_EXE_DIR)/$(BIN_TARGET)
 	touch .quick-install
 
 clean:
-	-$(RM) TAGS $(OBJECTS) $(BIN_TARGET) \\
+	-$(RM) TAGS $(OBJECTS) $(BIN_TARGET) $(LIB_TARGET) \\
 		$(INC_TARGET) $(DERIVED_HEADERS) *.~[0-9]~
 
 INC_CFILES = $(TARGET_CFILES)
@@ -379,6 +402,10 @@ $(TARGET)-local.h:
 # protection against multiple reads. FC, 02/08/95
 # header entry added to allow forcing the .h generation with make header
 # without having to touch the sources.
+
+$(INC_TARGET): $(TARGET)-local.h $(PIPS_MAKE_DEPEND_CFILES)
+	$(MAKE) header
+	
 header:
 	{ \\
 	echo "#ifndef ${dir_simple_name}_header_included" ;\\
@@ -390,10 +417,8 @@ header:
 	} > $(INC_TARGET).tmp
 	mv $(INC_TARGET).tmp $(INC_TARGET)
 
-$(INC_TARGET): $(TARGET)-local.h $(PIPS_MAKE_DEPEND_CFILES)
-	$(MAKE) header
-	
 depend: $(INC_TARGET) production-depend $(MAKEFILE)
+
 # Relance une compilation de $(INC_TARGET) en rajoutant la dependance sur les
 #	fichiers C :
 	PIPS_MAKE_DEPEND_CFILES="$(INC_CFILES)" $(MAKE) $(INC_TARGET)
@@ -426,7 +451,6 @@ fi
 
 echo
 
-)
-
 ### end main loop
 done
+
