# on 1996/07/11 13:00:17, coelho did: *** empty log message ***
git-svn-id: http://svn.cri.ensmp.fr/svn/pips/trunk@4166 32a0c1e6-9308-0410-80dd-f9d2257a62c7

diff --git a/src/Scripts/make/make-pips b/src/Scripts/make/make-pips
--- a/src/Scripts/make/make-pips
+++ b/src/Scripts/make/make-pips
@@ -1,7 +1,7 @@
 #! /bin/sh
 #
 # $RCSfile: make-pips,v $ version $Revision$
-# $Date: 1996/07/11 12:51:30 $, 
+# $Date: 1996/07/11 13:00:17 $, 
 #
 # (c) Fabien COELHO July 1996
 #
@@ -14,6 +14,37 @@ script=`basename $0`
 unset sides parts commands dirs libs pips newgen linear
 verb=':'
 job=$PIPS_MAKE
+
+#
+# misc utils
+
+verbose()
+{
+    echo "$script: $@" >&2
+}
+
+error()
+{
+    ret=$1
+    shift
+    verbose "$@"
+    exit $ret
+}
+
+#
+# check environment
+
+[ "$NEWGEN_DIR" ] || error 4 "newgen environment not set!"
+[ -d "$NEWGEN_DIR" ] || error 5 "invalid newgen environment!"
+
+[ "$LINEAR_DIR" ] || error 6 "linear environment not set!"
+[ -d "$LINEAR_DIR" ] || error 7 "invalid linear environment!"
+
+[ "$PIPS_DIR" ]   || error 8 "pips environment not set!"
+[ -d "$PIPS_DIR" ] || error 9 "invalid pips environment!"
+
+#
+# get options
 
 usage()
 {
@@ -41,11 +72,6 @@ usage()
 	 targets: make targets to require (e.g. clean all recompile diff...)
 EOF
     exit $ret
-}
-
-verbose()
-{
-    echo "$script: $@" >&2
 }
 
 while getopts hvNRPDplnbd:o: OPT
@@ -111,6 +137,7 @@ $verb "commands=$commands"
 for d in $dirs
 do
     $verb "dealing with $d"
+    test -d $d || error 3 "no $d directory!" 
     $job -C $d $libs $commands
 done
 
