# on 1996/08/20 09:54:57, coelho did: *** empty log message ***
git-svn-id: http://svn.cri.ensmp.fr/svn/pips/trunk@4768 32a0c1e6-9308-0410-80dd-f9d2257a62c7

diff --git a/src/Scripts/make/make-pips b/src/Scripts/make/make-pips
--- a/src/Scripts/make/make-pips
+++ b/src/Scripts/make/make-pips
@@ -1,7 +1,7 @@
 #! /bin/sh
 #
 # $RCSfile: make-pips,v $ version $Revision$
-# $Date: 1996/07/13 11:25:43 $, 
+# $Date: 1996/08/20 09:54:57 $, 
 #
 # (c) Fabien COELHO July 1996
 #
@@ -13,15 +13,13 @@ umask 2
 script=`basename $0`
 unset sides parts commands dirs libs pips newgen linear msg report where
 verb=':'
-job=$PIPS_MAKE
+job=${PIPS_MAKE:-gmake}
 
 #
 # misc utils
 
 verbose()
-{
-    echo "$script: $@" >&2
-}
+{ echo "$script: $@" >&2 ;}
 
 error()
 {
@@ -34,14 +32,25 @@ error()
 #
 # check environment
 
-[ "$NEWGEN_DIR" ] || error 4 "newgen environment not set!"
-[ -d "$NEWGEN_DIR" ] || error 5 "invalid newgen environment!"
+[ "$NEWGEN_ROOT" ] || error 4 "newgen environment not set!"
+[ -d "$NEWGEN_ROOT" ] || error 5 "invalid newgen environment!"
 
-[ "$LINEAR_DIR" ] || error 6 "linear environment not set!"
-[ -d "$LINEAR_DIR" ] || error 7 "invalid linear environment!"
+[ "$LINEAR_ROOT" ] || error 6 "linear environment not set!"
+[ -d "$LINEAR_ROOT" ] || error 7 "invalid linear environment!"
 
-[ "$PIPS_DIR" ]   || error 8 "pips environment not set!"
-[ -d "$PIPS_DIR" ] || error 9 "invalid pips environment!"
+[ "$PIPS_ROOT" ]   || error 8 "pips environment not set!"
+[ -d "$PIPS_ROOT" ] || error 9 "invalid pips environment!"
+
+#
+# get variables
+
+if [ -f ${PIPS_ROOT}/Include/define_libraries ]
+then
+    . ${PIPS_ROOT}/Include/define_libraries
+else
+    # default for bootstraping pips?
+    PIPS_ORDERED_LIBS='dev'
+fi
 
 #
 # get options
@@ -83,7 +92,7 @@ do
 	v) verb=verbose ;;
 	N) job="echo $PIPS_MAKE" ;;
 	R) sides="$sides RELEASEDIR"; msg="R${msg}" ;;
-	P) sides="$sides SRCDIR"; msg="P${msg}" ;;
+	P) sides="$sides ROOT/Src"; msg="P${msg}" ;;
 	D) sides="$sides DEVEDIR"; msg="D${msg}" ;;
 	p) parts="$parts PIPS" ; pips='1' ;;
 	l) parts="$parts LINEAR" ; linear='1' ;;
@@ -110,7 +119,7 @@ commands="$@ $commands"
 #
 # defaults:
 
-[ "$sides" ] || { sides="SRCDIR" ; msg="P$msg" ; }
+[ "$sides" ] || { sides="ROOT/Src" ; msg="P$msg" ; }
 [ "$parts" ] || { parts="PIPS" ; pips='1' ; }
 
 [ "$pips" ] && 
@@ -131,7 +140,7 @@ for p in $parts ;
 do 
     for s in $sides ;
     do
-	dirs="$dirs "`eval echo \$"${p}_${s}"`
+	dirs="$dirs "`eval echo \$"$p_$s"`
     done
 done
 
