# on 1995/10/09 10:46:28, oget did: clean before build
git-svn-id: http://svn.cri.ensmp.fr/svn/pips/trunk@2776 32a0c1e6-9308-0410-80dd-f9d2257a62c7

diff --git a/src/Scripts/make/make-pips b/src/Scripts/make/make-pips
--- a/src/Scripts/make/make-pips
+++ b/src/Scripts/make/make-pips
@@ -1,8 +1,8 @@
-#! /bin/sh
+#! /bin/sh -x
 #! /bin/sh -vx
 #
 # SCCS stuff:
-# $RCSfile: make-pips,v $ ($Date: 1995/10/05 09:14:38 $, )
+# $RCSfile: make-pips,v $ ($Date: 1995/10/09 10:46:28 $, )
 # version $Revision$
 # got on %D%, %T%
 #
@@ -78,7 +78,7 @@ PASSES=${PIPS_PASSES}
 #LIBS=`(cd $PIPS_LIBSRCDIR; echo [!M]*)`
 
 echo analyzing libraries ...
-analyze_libraries -p
+#analyze_libraries -p
 
 echo ordering libraries ...
 order_libraries -b
@@ -105,21 +105,32 @@ echo LIBS=$LIBS
 # build .a file for all libraries in Production
 if [ -n "$PRODUCTION" ]
 then
+
+if [ -n "$RECOMPILE" ]
+then
+	echo Cleaning libraries ...
+	for lib in $LIBS ; do
+		(cd ${PIPS_LIBSRCDIR}/${lib}; 
+			eval make $MAKE_OPTION clean $REDIRECT
+			eval make $MAKE_OPTION depend $REDIRECT)
+		if [ $? -ne 0 ] ; then
+			echo "Failed in cleaning library $lib in Production"
+			FAILURES="$FAILURES $lib (clean - P),"
+		fi
+	done
+fi
+
 for lib in $LIBS ; do
-	echo; echo
+	echo
 	(echo cd ${PIPS_LIBSRCDIR}/${lib} ; cd ${PIPS_LIBSRCDIR}/${lib}; 
 		echo "Making ${PIPS_LIBDIR}/lib${lib}.a"
-		if [ -n "$RECOMPILE" ]
-		then
-			eval make $MAKE_OPTION clean $REDIRECT
-			eval make $MAKE_OPTION depend $REDIRECT
-		fi ;
 		eval make $MAKE_OPTION recompile $REDIRECT)
 	if [ $? -ne 0 ] ; then
 		echo "Failed in building library $lib in Production"
 		FAILURES="$FAILURES $lib (P),"
 	fi
 done
+
 fi
 
 # build .a file for all libraries in Development
@@ -144,22 +155,30 @@ then
 	then
 		mkdir ${PIPS_BINDIR}
 	fi
-for pass in $PASSES ; do
-	echo; echo
-#	printenv
-	(echo cd ${PIPS_BINSRCDIR}/${pass}; cd ${PIPS_BINSRCDIR}/${pass}; 
-		echo "Making ${PIPS_BINDIR}/${pass}"
-		if [ -n "$RECOMPILE" ]
-		then
-			eval make $MAKE_OPTION clean $REDIRECT
-			eval make $MAKE_OPTION depend $REDIRECT
-		fi ;
-		eval make $MAKE_OPTION recompile $REDIRECT)
-	if [ $? -ne 0 ] ; then
-		echo " Failed in building ${PIPS_BINDIR}/${pass}"
-		FAILURES="$FAILURES $pass (P),"
+	if [ -n "$RECOMPILE" ]
+	then
+		echo Cleaning passes...
+		for pass in $PASSES ; do
+			(cd ${PIPS_BINSRCDIR}/${pass}; 
+				eval make $MAKE_OPTION clean $REDIRECT
+				eval make $MAKE_OPTION depend $REDIRECT)
+			if [ $? -ne 0 ] ; then
+				echo " Failed in building ${PIPS_BINDIR}/${pass}"
+				FAILURES="$FAILURES $pass (clean - P),"
+			fi
+		done
 	fi
-done
+
+	for pass in $PASSES ; do
+		echo; echo
+		(echo cd ${PIPS_BINSRCDIR}/${pass}; cd ${PIPS_BINSRCDIR}/${pass}; 
+			echo "Making ${PIPS_BINDIR}/${pass}"
+			eval make $MAKE_OPTION recompile $REDIRECT)
+		if [ $? -ne 0 ] ; then
+			echo " Failed in building ${PIPS_BINDIR}/${pass}"
+			FAILURES="$FAILURES $pass (P),"
+		fi
+	done
 fi
 
 # build passes
