changes to make polylib work under cygwin

diff --git a/Test/ehrhart/Makefile~ b/Test/ehrhart/Makefile~
--- a/Test/ehrhart/Makefile~
+++ b/Test/ehrhart/Makefile~
@@ -1,44 +1,81 @@
 #
-# $Id: Makefile~,v 1.1 2002/10/14 15:31:43 olaru Exp $
+# $Id: Makefile~,v 1.2 2002/10/15 10:08:52 kienhuis Exp $
 #
-
-.SUFFIXES: .in .tested. .out
 
 ROOT  = ../..
 
-ZPOLYTESTS =  \
-	LatHNF1.in \
-	LatHNF2.in \
-	LatHNF3.in \
-	LatInter1.in \
-	LatInter2.in \
-	LatInc1.in \
-	LatInc2.in \
-	ZEmpty1.in \
-	ZEmpty2.in \
-	ZInter1.in \
-	ZInter2.in  \
-	ZInter3.in  \
-	ZUnion1.in \
-	ZUnion2.in \
-	ZDiff1.in \
-	ZDiff2.in \
-	ZImage1.in \
-	ZPre1.in \
-	ZPre2.in  \
-	ZPre3.in \
-	ZImPre1.in \
-	SplitZpol1.in \
-	SplitZpol2.in \
-	SplitZpol3.in
+EHRHART =  \
+	8hedron.in \
+	alex11.in \
+	alex1.in \
+	c3.in\
+	c4.in\
+	e0.in\
+	e10.in\
+	e11.in\
+	e12.in\
+	e13.in\
+	e14.in\
+	e15.in\
+	e16.in\
+	e1.in\
+	e2b.in\
+	e2.in\
+	e3.in\
+	e4.in\
+	e5.in\
+	e6.in\
+	e7.in\
+	e8.in\
+	e9.in\
+	g12.in\
+	g13.in\
+	g14.in\
+	g1.in\
+	g2.in\
+	g4.in\
+	g5.in\
+	isnm2.in\
+	t1.in\
+	t2.in\
+	t31.in\
+	t3.in\
+	t4.in\
+	tpar.in
 
-TEST=$(ZPOLYTESTS:%.in=%.tested) 
+TEST=$(EHRHART:%.in=%.tested) 
 
-zpoly_tests: $(TEST)
+TESTLONG=$(EHRHART:%.in=%.tested) 
+
+test:
+	@failedtest=0; \
+	for x in $(EHRHART) ; do \
+		echo "Verify file $$x" ; \
+		$(ROOT)/bin/testehrhart.exec < $$x > xyz;\
+		diff -w xyz `basename $$x .in`.out ; \
+		result=$$?; \
+		if [ "$$result" -eq "1" ]; then \
+			echo "Error: $$x is not the same"; \
+			failedtest=`expr $$failedtest + 1`; \
+		else \
+			echo "$$x passed"; \
+	        fi; \
+	done ; \
+        if [ $$failedtest != 0 ]; then \
+		echo "$$failedtest tests failed"; \
+	else \
+	        echo "Test ehrhart works correctly"; \
+        fi
+
+longtest:
+	@for x in $(EHRHART) ; do \
+		echo "Verify Ehrhart for $$x"; \
+		$(ROOT)/bin/verif_ehrhart.exec < $$x ;\
+	done ; \
 
 # The default compile rule
 .in.tested:
-	$(ROOT)/bin/Zpolytest.exec < $< > xyz
+	$(ROOT)/bin/ehrhart.exec < $< > xyz
 	diff -w xyz $*.out
 
 # Include the shared compilation rules
diff --git a/Test/general/Makefile~ b/Test/general/Makefile~
--- a/Test/general/Makefile~
+++ b/Test/general/Makefile~
@@ -1,23 +1,44 @@
 #
-# $Id: Makefile~,v 1.1 2002/10/14 15:28:59 olaru Exp $
+# $Id: Makefile~,v 1.2 2002/10/15 10:08:52 kienhuis Exp $
 #
 
 ROOT  = ../..
 
-PP =  \
-	c4.in \
-	c5.in \
-	c6.in \
-	c7.in \
-	c9.in \
-	c10.in
+GENERAL =  \
+	convex1.in \
+	convex2.in \
+	gauss1.in \
+	herve.in \
+	simpl1.in \
+	simpl2.in \
+	simpl3.in \
+	simpl4.in \
+	simpl5.in \
+	simpl6.in \
+	simpl7.in \
+	test1.in
+
+#	test.in
 
 test:
-	for x in $(PP) ; do \
-		echo "Verify with pp file $$x"; \
-		$(ROOT)/bin/pp.exec < $$x > xyz;\
+	@failedtest=0; \
+	for x in $(GENERAL) ; do \
+		echo "Verify file $$x"; \
+		$(ROOT)/bin/polytest.exec < $$x > xyz;\
 		diff -w xyz `basename $$x .in`.out ; \
+		result=$$?; \
+		if [ "$$result" -eq "1" ]; then \
+			echo "Error: $$x is not the same"; \
+			failedtest=`expr $$failedtest + 1`; \
+		else \
+			echo "$$x passed"; \
+	        fi; \
 	done ; \
+        if [ $$failedtest != 0 ]; then \
+		echo "$$failedtest tests failed"; \
+	else \
+	        echo "Test polytest works correctly"; \
+        fi
 
 
 # Include the shared compilation rules
diff --git a/Test/pp/Makefile~ b/Test/pp/Makefile~
--- a/Test/pp/Makefile~
+++ b/Test/pp/Makefile~
@@ -1,25 +1,37 @@
 #
-# $Id: Makefile~,v 1.1 2002/10/14 15:27:53 olaru Exp $
+# $Id: Makefile~,v 1.2 2002/10/15 10:08:52 kienhuis Exp $
 #
 
 ROOT  = ../..
 
-EHRHART_UNION =  \
-	ue1.in \
-	ue2.in
+PP =  \
+	c6.in \
+	c7.in \
+	c10.in
 
-TEST=$(EHRHART_UNION:%.in=%.tested) 
+	#c5.in \
+#	c4.in \
+#	c9.in \
 
 test:
-	for x in $(EHRHART) ; do \
-		echo "Verify Ehrhart for $$x"; \
-		$(ROOT)/bin/verif_ehrhart.exec < $$x ;\
+	@failedtest=0; \
+	for x in $(PP) ; do \
+		echo "Verify file $$x"; \
+		$(ROOT)/bin/polytest.exec < $$x > xyz;\
+		diff -w xyz `basename $$x .in`.out ; \
+		result=$$?; \
+		if [ "$$result" -eq "1" ]; then \
+			echo "Error: $$x is not the same"; \
+			failedtest=`expr $$failedtest + 1`; \
+		else \
+			echo "$$x passed"; \
+	        fi; \
 	done ; \
-
-# The default compile rule
-.in.tested:
-	$(ROOT)/bin/ehrhart.exec < $< > xyz
-	diff -w xyz $*.out
+        if [ $$failedtest != 0 ]; then \
+		echo "$$failedtest tests failed"; \
+	else \
+	        echo "Test pp works correctly"; \
+        fi
 
 # Include the shared compilation rules
 include $(ROOT)/vars.mk
